apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: clojure-todo-api
build:
  artifacts:
    - image: clojure-todo-api
      context: ../app
      docker:
        dockerfile: ./Dockerfile
  local:
    push: false
    useBuildkit: true
manifests:
  helm:
    releases:
      - name: clojure-todo-api
        chartPath: app/helm/deployment
